#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

enum BerryFirmness
{
    BERRY_FIRMNESS_UNKNOWN,
    BERRY_FIRMNESS_VERY_SOFT,
    BERRY_FIRMNESS_SOFT,
    BERRY_FIRMNESS_HARD,
    BERRY_FIRMNESS_VERY_HARD,
    BERRY_FIRMNESS_SUPER_HARD,
};

enum BerryColor
{
    BERRY_COLOR_RED,
    BERRY_COLOR_BLUE,
    BERRY_COLOR_PURPLE,
    BERRY_COLOR_GREEN,
    BERRY_COLOR_YELLOW,
    BERRY_COLOR_PINK,
};

enum __attribute__((__packed__)) Flavor
{
    FLAVOR_SPICY,
    FLAVOR_DRY,
    FLAVOR_SWEET,
    FLAVOR_BITTER,
    FLAVOR_SOUR,
    FLAVOR_COUNT,
};

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"
#define BERRY_TREE_ROUTE_102_PECHA         1
#define BERRY_TREE_ROUTE_102_ORAN          2
#define BERRY_TREE_ROUTE_104_LUM           3
#define BERRY_TREE_ROUTE_104_SITRUS_1      4
#define BERRY_TREE_ROUTE_103_LEPPA_1       5
#define BERRY_TREE_ROUTE_103_LEPPA_2       6
#define BERRY_TREE_ROUTE_103_SITRUS_1      7
#define BERRY_TREE_ROUTE_104_PECHA_1       8
#define BERRY_TREE_ROUTE_104_LUM_1         9
#define BERRY_TREE_ROUTE_104_LUM_2         10
#define BERRY_TREE_ROUTE_104_SITRUS_2      11
#define BERRY_TREE_ROUTE_104_SITRUS        12
#define BERRY_TREE_ROUTE_104_PECHA         13
#define BERRY_TREE_ROUTE_123_SALAC_1       14
#define BERRY_TREE_ROUTE_123_LIECHI_1      15
#define BERRY_TREE_ROUTE_110_NANAB_1       16
#define BERRY_TREE_ROUTE_110_NANAB_2       17
#define BERRY_TREE_ROUTE_110_NANAB_3       18
#define BERRY_TREE_ROUTE_111_RAZZ_1        19
#define BERRY_TREE_ROUTE_111_RAZZ_2        20
#define BERRY_TREE_ROUTE_112_RAWST_1       21
#define BERRY_TREE_ROUTE_112_OCCA_1        22
#define BERRY_TREE_ROUTE_112_OCCA_2        23
#define BERRY_TREE_ROUTE_112_RAWST_2       24
#define BERRY_TREE_ROUTE_116_PINAP_1       25
#define BERRY_TREE_ROUTE_116_CHESTO_1      26
#define BERRY_TREE_ROUTE_117_SITRUS_1      27
#define BERRY_TREE_ROUTE_117_SITRUS_2      28
#define BERRY_TREE_ROUTE_117_SITRUS_3      29
#define BERRY_TREE_ROUTE_123_LIECHI_2      30
#define BERRY_TREE_ROUTE_118_SITRUS_1      31
#define BERRY_TREE_ROUTE_118_SOIL          32
#define BERRY_TREE_ROUTE_118_SITRUS_2      33
#define BERRY_TREE_ROUTE_119_KEBIA_1       34
#define BERRY_TREE_ROUTE_119_KEBIA_2       35
#define BERRY_TREE_ROUTE_119_KEBIA_3       36
#define BERRY_TREE_ROUTE_120_COBA_1        37
#define BERRY_TREE_ROUTE_120_COBA_2        38
#define BERRY_TREE_ROUTE_120_COBA_3        39
#define BERRY_TREE_ROUTE_120_TANGA_1       40
#define BERRY_TREE_ROUTE_120_TANGA_2       41
#define BERRY_TREE_ROUTE_120_TANGA_3       42
#define BERRY_TREE_ROUTE_120_AGUAV_2       43
#define BERRY_TREE_ROUTE_120_AGUAV_1       44
#define BERRY_TREE_ROUTE_120_MAGO_2        45
#define BERRY_TREE_ROUTE_120_MAGO_1        46
#define BERRY_TREE_ROUTE_121_CHILAN_1      47
#define BERRY_TREE_ROUTE_121_CHILAN_2      48
#define BERRY_TREE_ROUTE_121_PASSHO_1     49
#define BERRY_TREE_ROUTE_121_PASSHO_2      50
#define BERRY_TREE_ROUTE_121_CUSTAP_1      51
#define BERRY_TREE_ROUTE_121_LUM_1         52
#define BERRY_TREE_ROUTE_121_LUM_2         53
#define BERRY_TREE_ROUTE_121_CUSTAP_2      54
#define BERRY_TREE_ROUTE_115_FIGY          55
#define BERRY_TREE_ROUTE_115_WIKI          56
#define BERRY_TREE_UNUSED                  57
#define BERRY_TREE_ROUTE_123_GANLON_1      58
#define BERRY_TREE_ROUTE_123_GANLON_2      59
#define BERRY_TREE_ROUTE_123_APICOT_1      60
#define BERRY_TREE_ROUTE_123_APICOT_2      61
#define BERRY_TREE_ROUTE_123_LEPPA_1       62
#define BERRY_TREE_ROUTE_123_SOIL          63
#define BERRY_TREE_ROUTE_123_LEPPA_2       64
#define BERRY_TREE_ROUTE_123_STARF_1       65
#define BERRY_TREE_ROUTE_116_CHESTO_2      66
#define BERRY_TREE_ROUTE_116_PINAP_2       67
#define BERRY_TREE_ROUTE_114_SITRUS_1      68
#define BERRY_TREE_ROUTE_115_SHUCA         69
#define BERRY_TREE_ROUTE_115_CHARTI        70
#define BERRY_TREE_ROUTE_115_HABAN         71
#define BERRY_TREE_ROUTE_123_STARF_2       72
#define BERRY_TREE_ROUTE_123_SALAC_2       73
#define BERRY_TREE_ROUTE_123_QUALOT_3      74
#define BERRY_TREE_ROUTE_104_LUM_3         75
#define BERRY_TREE_ROUTE_104_PECHA_2       76
#define BERRY_TREE_ROUTE_114_SITRUS_2      77
#define BERRY_TREE_ROUTE_114_SITRUS_3      78
#define BERRY_TREE_ROUTE_123_QUALOT_4      79
#define BERRY_TREE_ROUTE_111_ORAN_1        80
#define BERRY_TREE_ROUTE_111_ORAN_2        81
#define BERRY_TREE_ROUTE_130_LIECHI        82
#define BERRY_TREE_ROUTE_119_RINDO_1       83
#define BERRY_TREE_ROUTE_119_RINDO_2       84
#define BERRY_TREE_ROUTE_119_SITRUS        85
#define BERRY_TREE_ROUTE_119_LEPPA         86
#define BERRY_TREE_ROUTE_123_PECHA         87
#define BERRY_TREE_ROUTE_123_SITRUS        88
#define BERRY_TREE_ROUTE_123_RAWST         89
#define BERRY_TREE_METEOR_LIECHI           90
#define BERRY_TREE_METEOR_PEAK_SALAC       91
#define BERRY_TREE_METEOR_PEAK_STARF       92
#define BERRY_TREE_RUSTBORO_PIER_CHESTO_1  93
#define BERRY_TREE_RUSTBORO_PIER_CHESTO_2  94
#define BERRY_TREE_ROUTE_123_PETAYA_1      95
#define BERRY_TREE_ROUTE_123_PETAYA_2      96
#define BERRY_TREE_ROUTE_103_SITRUS_2      97
#define BERRY_TREE_ROUTE_103_CUSTAP_1      98
#define BERRY_TREE_ROUTE_103_CUSTAP_2      99
#define BERRY_TREE_ROUTE_103_LUM_1         100
#define BERRY_TREE_ROUTE_103_LUM_2         101
#define BERRY_TREE_ROUTE_103_CHERI_1       102
#define BERRY_TREE_ROUTE_103_CHERI_2       103
#define BERRY_TREE_ROUTE_104_ORAN_2        104
#define BERRY_TREE_ROUTE_104_ORAN_1        105
#define BERRY_TREE_ROUTE_104_CHERI_2       106
#define BERRY_TREE_ROUTE_104_CHERI_1       107
#define BERRY_TREE_ROUTE_104_LEPPA         108
#define BERRY_TREE_ROUTE_115_KELPSY_1      109
#define BERRY_TREE_ROUTE_115_KELPSY_2      110
#define BERRY_TREE_ROUTE_115_KELPSY_3      111
#define BERRY_TREE_ROUTE_115_BLUK_1        112
#define BERRY_TREE_ROUTE_115_BLUK_2        113
#define BERRY_TREE_ROUTE_103_LEPPA         114

// Remainder are unused

#define BERRY_TREES_COUNT 128

#endif // GUARD_CONSTANTS_BERRY_H
