#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER                        1
#define TRAINER_GABRIELLE                     2
#define TRAINER_MARCEL                        3
#define TRAINER_ALBERTO                       4
#define TRAINER_ED                            5
#define TRAINER_DECLAN                        6
#define TRAINER_FREDRICK                      7
#define TRAINER_ZANDER                        8
#define TRAINER_ARCHIE                        9
#define TRAINER_LEAH                         10
#define TRAINER_DAISY                        11
#define TRAINER_ROSE                         12
#define TRAINER_FELIX                        13
#define TRAINER_VIOLET                       14
#define TRAINER_DUSTY                        15
#define TRAINER_CHIP                         16
#define TRAINER_FOSTER                       17
#define TRAINER_LOLA                         18
#define TRAINER_AUSTINA                      19
#define TRAINER_GWEN                         20
#define TRAINER_RICKY                        21
#define TRAINER_SIMON                        22
#define TRAINER_CHARLIE                      23
#define TRAINER_RANDALL                      24
#define TRAINER_PARKER                       25
#define TRAINER_GEORGE                       26
#define TRAINER_BERKE                        27
#define TRAINER_BRAXTON                      28
#define TRAINER_VINCENT                      29
#define TRAINER_LEROY                        30
#define TRAINER_WILTON                       31
#define TRAINER_EDGAR                        32
#define TRAINER_ALBERT                       33
#define TRAINER_SAMUEL                       34
#define TRAINER_VITO                         35
#define TRAINER_OWEN                         36
#define TRAINER_WARREN                       37
#define TRAINER_MARY                         38
#define TRAINER_ALEXIA                       39
#define TRAINER_JODY                         40
#define TRAINER_WENDY                        41
#define TRAINER_KEIRA                        42
#define TRAINER_BROOKE                       43
#define TRAINER_JENNIFER                     44
#define TRAINER_HOPE                         45
#define TRAINER_SHANNON                      46
#define TRAINER_MICHELLE                     47
#define TRAINER_CAROLINE                     48
#define TRAINER_JULIE                        49
#define TRAINER_PATRICIA                     50
#define TRAINER_KINDRA                       51
#define TRAINER_TAMMY                        52
#define TRAINER_VALERIE                      53
#define TRAINER_TASHA                        54
#define TRAINER_CINDY                        55
#define TRAINER_DAPHNE                       56
#define TRAINER_BRIANNA                      57
#define TRAINER_NAOMI                        58
#define TRAINER_MELISSA                      59
#define TRAINER_SHEILA                       60
#define TRAINER_SHIRLEY                      61
#define TRAINER_JESSICA                      62
#define TRAINER_CONNIE                       63
#define TRAINER_BRIDGET                      64
#define TRAINER_OLIVIA                       65
#define TRAINER_TIFFANY                      66
#define TRAINER_WINSTON                      67
#define TRAINER_MOLLIE                       68
#define TRAINER_GARRET                       69
#define TRAINER_STEVE                        70
#define TRAINER_THALIA                       71
#define TRAINER_MARK                         72
#define TRAINER_LUIS                         73
#define TRAINER_DOMINIK                      74
#define TRAINER_DOUGLAS                      75
#define TRAINER_DARRIN                       76
#define TRAINER_TONY                         77
#define TRAINER_JEROME                       78
#define TRAINER_MATTHEW                      79
#define TRAINER_DAVID                        80
#define TRAINER_SPENCER                      81
#define TRAINER_ROLAND                       82
#define TRAINER_NOLEN                        83
#define TRAINER_STAN                         84
#define TRAINER_BARRY                        85
#define TRAINER_DEAN                         86
#define TRAINER_RODNEY                       87
#define TRAINER_RICHARD                      88
#define TRAINER_HERMAN                       89
#define TRAINER_SANTIAGO                     90
#define TRAINER_GILBERT                      91
#define TRAINER_FRANKLIN                     92
#define TRAINER_KEVIN                        93
#define TRAINER_JACK                         94
#define TRAINER_DUDLEY                       95
#define TRAINER_CHAD                         96
#define TRAINER_TAKAO                        97
#define TRAINER_HITOSHI                      98
#define TRAINER_KIYO                         99
#define TRAINER_KOICHI                      100
#define TRAINER_NOB                         101
#define TRAINER_YUJI                        102
#define TRAINER_DAISUKE                     103
#define TRAINER_ATSUSHI                     104
#define TRAINER_KIRK                        105
#define TRAINER_SHAWN                       106
#define TRAINER_FERNANDO                    107
#define TRAINER_DALTON                      108
#define TRAINER_COLE                        109
#define TRAINER_JEFF                        110
#define TRAINER_AXLE                        111
#define TRAINER_JACE                        112
#define TRAINER_KEEGAN                      113
#define TRAINER_BERNIE                      114
#define TRAINER_DREW                        115
#define TRAINER_BEAU                        116
#define TRAINER_LARRY                       117
#define TRAINER_SHANE                       118
#define TRAINER_JUSTIN                      119
#define TRAINER_ETHAN                       120
#define TRAINER_AUTUMN                      121
#define TRAINER_TRAVIS                      122
#define TRAINER_BRENT                       123
#define TRAINER_DONALD                      124
#define TRAINER_TAYLOR                      125
#define TRAINER_JEFFREY                     126
#define TRAINER_DEREK                       127
#define TRAINER_EDWARD                      128
#define TRAINER_PRESTON                     129
#define TRAINER_VIRGIL                      130
#define TRAINER_BLAKE                       131
#define TRAINER_WILLIAM                     132
#define TRAINER_JOSHUA                      133
#define TRAINER_CAMERON                     134
#define TRAINER_JACLYN                      135
#define TRAINER_HANNAH                      136
#define TRAINER_SAMANTHA                    137
#define TRAINER_MAURA                       138
#define TRAINER_KAYLA                       139
#define TRAINER_ALEXIS                      140
#define TRAINER_JACKI                       141 
#define TRAINER_WALTER                      142 
#define TRAINER_MICAH                       143
#define TRAINER_THOMAS                      144
#define TRAINER_SIDNEY                      145
#define TRAINER_PHOEBE                      146
#define TRAINER_GLACIA                      147
#define TRAINER_DRAKE                       148
#define TRAINER_ROXANNE                     149
#define TRAINER_BRAWLY                      150
#define TRAINER_WATTSON                     151
#define TRAINER_FLANNERY                    152
#define TRAINER_NORMAN                      153
#define TRAINER_WINONA                      154
#define TRAINER_TATE_AND_LIZA               155
#define TRAINER_JUAN                        156
#define TRAINER_JERRY                       157
#define TRAINER_TED                         158
#define TRAINER_PAUL                        159
#define TRAINER_KAREN                       160
#define TRAINER_GEORGIA                     161
#define TRAINER_KATE_AND_JOY                162
#define TRAINER_ANNA_AND_MEG                163
#define TRAINER_VICTOR                      164
#define TRAINER_MIGUEL                      165
#define TRAINER_COLTON                      166
#define TRAINER_VICTORIA                    167
#define TRAINER_VANESSA                     168
#define TRAINER_BETHANY                     169
#define TRAINER_ISABEL                      170
#define TRAINER_TIMOTHY                     171
#define TRAINER_VICKY                       172
#define TRAINER_SHELBY                      173
#define TRAINER_CALVIN                      174
#define TRAINER_BILLY                       175
#define TRAINER_JOSH                        176
#define TRAINER_TOMMY                       177
#define TRAINER_JOEY                        178
#define TRAINER_BEN                         179
#define TRAINER_QUINCY                      180
#define TRAINER_KATELYNN                    181
#define TRAINER_JAYLEN                      182
#define TRAINER_DILLON                      183
#define TRAINER_EDDIE                       184
#define TRAINER_ALLEN                       185
#define TRAINER_TIMMY                       186
#define TRAINER_WALLACE                     187
#define TRAINER_ANDREW                      188
#define TRAINER_IVAN                        189
#define TRAINER_CLAUDE                      190
#define TRAINER_ELLIOT                      191
#define TRAINER_NED                         192
#define TRAINER_DALE                        193
#define TRAINER_NOLAN                       194
#define TRAINER_BARNY                       195
#define TRAINER_WADE                        196
#define TRAINER_CARTER                      197
#define TRAINER_RONALD                      198
#define TRAINER_JACOB                       199
#define TRAINER_ANTHONY                     200
#define TRAINER_BENJAMIN                    201
#define TRAINER_ABIGAIL                     202
#define TRAINER_JASMINE                     203
#define TRAINER_DYLAN                       204
#define TRAINER_MARIA                       205
#define TRAINER_CAMDEN                      206
#define TRAINER_DEMETRIUS                   207
#define TRAINER_ISAIAH                      208
#define TRAINER_PABLO                       209
#define TRAINER_CHASE                       210
#define TRAINER_ISOBEL                      211
#define TRAINER_DONNY                       212
#define TRAINER_TALIA                       213
#define TRAINER_KATELYN                     214
#define TRAINER_ALLISON                     215
#define TRAINER_NICOLAS                     216
#define TRAINER_AARON                       217
#define TRAINER_PERRY                       218
#define TRAINER_HUGH                        219
#define TRAINER_PHIL                        220
#define TRAINER_JARED                       221
#define TRAINER_HUMBERTO                    222
#define TRAINER_PRESLEY                     223
#define TRAINER_EDWARDO                     224
#define TRAINER_COLIN                       225
#define TRAINER_ROBERT                      226
#define TRAINER_BENNY                       227
#define TRAINER_CHESTER                     228
#define TRAINER_ALEX                        229
#define TRAINER_BECK                        230
#define TRAINER_YASU                        231
#define TRAINER_TAKASHI                     232
#define TRAINER_DIANNE                      233
#define TRAINER_JANI                        234
#define TRAINER_LAO                         235
#define TRAINER_LUNG                        236
#define TRAINER_JOCELYN                     237
#define TRAINER_LAURA                       238
#define TRAINER_CYNDY                       239
#define TRAINER_CORA                        240
#define TRAINER_PAULA                       241
#define TRAINER_MADELINE                    242
#define TRAINER_CLARISSA                    243
#define TRAINER_ANGELICA                    244
#define TRAINER_BEVERLY                     245
#define TRAINER_IMANI                       246
#define TRAINER_KYLA                        247
#define TRAINER_DENISE                      248
#define TRAINER_BETH                        249
#define TRAINER_TARA                        250
#define TRAINER_MISSY                       251
#define TRAINER_JOLINE                      252
#define TRAINER_JENNY                       253
#define TRAINER_GRACE                       254
#define TRAINER_TANYA                       255
#define TRAINER_SHARON                      256
#define TRAINER_NIKKI                       257
#define TRAINER_BRENDA                      258
#define TRAINER_KATIE                       259
#define TRAINER_SUSIE                       260
#define TRAINER_KARA                        261
#define TRAINER_DANA                        262
#define TRAINER_SIENNA                      263
#define TRAINER_DEBRA                       264
#define TRAINER_LINDA                       265
#define TRAINER_KAYLEE                      266
#define TRAINER_LAUREL                      267
#define TRAINER_CARLEE                      268
#define TRAINER_HEIDI                       269
#define TRAINER_BECKY                       270
#define TRAINER_CAROL                       271
#define TRAINER_NANCY                       272
#define TRAINER_MARTHA                      273
#define TRAINER_DIANA                       274
#define TRAINER_CEDRIC                      275
#define TRAINER_IRENE                       276
#define TRAINER_AMY_AND_LIV                 277
#define TRAINER_GINA_AND_MIA                278
#define TRAINER_MIU_AND_YUKI                279
#define TRAINER_HUEY                        280
#define TRAINER_EDMOND                      281
#define TRAINER_ERNEST                      282
#define TRAINER_DWAYNE                      283
#define TRAINER_PHILLIP                     284
#define TRAINER_LEONARD                     285
#define TRAINER_DUNCAN                      286
#define TRAINER_ELI                         287
#define TRAINER_ANNIKA                      288
#define TRAINER_JAZMYN                      289
#define TRAINER_JONAS                       290
#define TRAINER_KAYLEY                      291
#define TRAINER_AURON                       292
#define TRAINER_KELVIN                      293
#define TRAINER_MARLEY                      294
#define TRAINER_REYNA                       295
#define TRAINER_HUDSON                      296
#define TRAINER_CONOR                       297
#define TRAINER_EDWIN                       298
#define TRAINER_HECTOR                      299
#define TRAINER_ISAAC                       300
#define TRAINER_DAVIS                       301
#define TRAINER_MITCHELL                    302
#define TRAINER_LYDIA                       303
#define TRAINER_HALLE                       304
#define TRAINER_GARRISON                    305
#define TRAINER_JACKSON                     306
#define TRAINER_LORENZO                     307
#define TRAINER_SEBASTIAN                   308
#define TRAINER_CATHERINE                   309
#define TRAINER_JENNA                       310
#define TRAINER_SOPHIA                      311
#define TRAINER_JULIO                       312
#define TRAINER_MARC                        313
#define TRAINER_BRENDEN                     314
#define TRAINER_LILITH                      315
#define TRAINER_CRISTIAN                    316
#define TRAINER_SYLVIA                      317
#define TRAINER_LEONARDO                    318
#define TRAINER_ATHENA                      319
#define TRAINER_HARRISON                    320
#define TRAINER_CLARENCE                    321
#define TRAINER_TERRY                       322
#define TRAINER_NATE                        323
#define TRAINER_KATHLEEN                    324
#define TRAINER_CLIFFORD                    325
#define TRAINER_NICHOLAS                    326
#define TRAINER_MACEY                       327
#define TRAINER_PAXTON                      328
#define TRAINER_ISABELLA                    329
#define TRAINER_JONATHAN                    330
#define TRAINER_TIANA                       331
#define TRAINER_HALEY                       332
#define TRAINER_JANICE                      333
#define TRAINER_SALLY                       334
#define TRAINER_ROBIN                       335
#define TRAINER_ANDREA                      336
#define TRAINER_CRISSY                      337
#define TRAINER_RICK                        338
#define TRAINER_LYLE                        339
#define TRAINER_JOSE                        340
#define TRAINER_DOUG                        341
#define TRAINER_GREG                        342
#define TRAINER_KENT                        343
#define TRAINER_JAMES                       344 
#define TRAINER_BRICE                       345
#define TRAINER_TRENT                       346
#define TRAINER_LENNY                       347
#define TRAINER_LUCAS                       348
#define TRAINER_ALAN                        349
#define TRAINER_CLARK                       350
#define TRAINER_ERIC                        351
#define TRAINER_MIKE                        352
#define TRAINER_DEZ_AND_LUKE                353
#define TRAINER_LEA_AND_JED                 354
#define TRAINER_KIRA_AND_DAN                355
#define TRAINER_JOHANNA                     356
#define TRAINER_GERALD                      357
#define TRAINER_VIVIAN                      358
#define TRAINER_DANIELLE                    359
#define TRAINER_HIDEO                       360
#define TRAINER_KEIGO                       361
#define TRAINER_RILEY                       362
#define TRAINER_FLINT                       363
#define TRAINER_ASHLEY                      364
#define TRAINER_JONAH                       365
#define TRAINER_HENRY                       366
#define TRAINER_ROGER                       367
#define TRAINER_ALEXA                       368
#define TRAINER_RUBEN                       369
#define TRAINER_KOJI                        370
#define TRAINER_WAYNE                       371
#define TRAINER_AIDAN                       372
#define TRAINER_REED                        373
#define TRAINER_TISHA                       374
#define TRAINER_TORI_AND_TIA                375
#define TRAINER_KIM_AND_IRIS                376
#define TRAINER_TYRA_AND_IVY                377
#define TRAINER_MEL_AND_PAUL                378
#define TRAINER_JOHN_AND_JAY                379
#define TRAINER_RELI_AND_IAN                380
#define TRAINER_LILA_AND_ROY                381
#define TRAINER_LISA_AND_RAY                382
#define TRAINER_CHRIS                       383
#define TRAINER_DAWSON                      384
#define TRAINER_SARAH                       385
#define TRAINER_DARIAN                      386
#define TRAINER_HAILEY                      387
#define TRAINER_CHANDLER                    388
#define TRAINER_KALEB                       389
#define TRAINER_JOSEPH                      390
#define TRAINER_ALYSSA                      391
#define TRAINER_MARCOS                      392
#define TRAINER_RHETT                       393
#define TRAINER_TYRON                       394
#define TRAINER_CELINA                      395
#define TRAINER_BIANCA                      396
#define TRAINER_HAYDEN                      397
#define TRAINER_SOPHIE                      398
#define TRAINER_COBY                        399
#define TRAINER_LAWRENCE                    400
#define TRAINER_WYATT                       401
#define TRAINER_ANGELINA                    402
#define TRAINER_KAI                         403
#define TRAINER_CHARLOTTE                   404
#define TRAINER_DEANDRE                     405
#define TRAINER_DARCY                       406
#define TRAINER_PETE                        407
#define TRAINER_ISABELLE                    408
#define TRAINER_ANDRES                      409
#define TRAINER_JOSUE                       410
#define TRAINER_CAMRON                      411
#define TRAINER_CORY                        412
#define TRAINER_CAROLINA                    413
#define TRAINER_ELIJAH                      414
#define TRAINER_CELIA                       415
#define TRAINER_BRYAN                       416
#define TRAINER_BRANDEN                     417
#define TRAINER_BRYANT                      418
#define TRAINER_SHAYLA                      419
#define TRAINER_KYRA                        420
#define TRAINER_JAIDEN                      421
#define TRAINER_ALIX                        422
#define TRAINER_HELENE                      423
#define TRAINER_MARLENE                     424
#define TRAINER_DEVAN                       425
#define TRAINER_JOHNSON                     426
#define TRAINER_MELINA                      427
#define TRAINER_BRANDI                      428
#define TRAINER_AISHA                       429
#define TRAINER_MAKAYLA                     430
#define TRAINER_FABIAN                      431
#define TRAINER_DAYTON                      432
#define TRAINER_RACHEL                      433
#define TRAINER_LEONEL                      434
#define TRAINER_CALLIE                      435
#define TRAINER_CALE                        436
#define TRAINER_MYLES                       437
#define TRAINER_PAT                         438
#define TRAINER_CRISTIN                     439
#define TRAINER_ANGELO                      440
#define TRAINER_DARIUS                      441
#define TRAINER_STEVEN                      442
#define TRAINER_ANABEL                      443
#define TRAINER_TUCKER                      444
#define TRAINER_SPENSER                     445
#define TRAINER_GRETA                       446
#define TRAINER_NOLAND                      447
#define TRAINER_LUCY                        448
#define TRAINER_BRANDON                     449
#define TRAINER_MARIELA                     450 
#define TRAINER_ALVARO                      451
#define TRAINER_EVERETT                     452
#define TRAINER_TEST_TRAINER                453 //test trainer     
#define TRAINER_SLATEPORT_BOSS              454 //test trainer
#define TRAINTER_MTPYRE_BOSS                455 //test trainer
#define TRAINER_FIONA                       456
#define TRAINER_MAXINE                      457
#define TRAINER_LINDON                      458
#define TRAINER_VELOMACHUS                  459
#define TRAINER_QUENTIN                     460
#define TRAINER_EZRA                        461
#define TRAINER_EITHAN                      462
#define TRAINER_YERIN                       463
#define TRAINER_DAISHOU                     464
#define TRAINER_DIMITRI                     465
#define TRAINER_LUMIS                       466
#define TRAINER_UMBRA                       467
#define TRAINER_CASSIAS                     468
#define TRAINER_LONG                        469
#define TRAINER_TYLER                       470
#define TRAINER_EGG                         471
#define TRAINER_DUNK                        472
#define TRAINER_HARMONY                     473
#define TRAINER_MERCY                       474
#define TRAINER_ZIEL                        475
#define TRAINER_FRANK                       476
#define TRAINER_RIVALSQUIRTLE               477
#define TRAINER_RIVALFENNEKIN               478
#define TRAINER_RIVALCHIKORITA              479
#define TRAINER_JEBEDIAH                    480
#define TRAINER_JOEL                        481
#define TRAINER_LAURENT                     482

//       You can freely add trainers to this list until you hit 863, then some fiddling will need to e done. :)
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_EMERALD     483
#define MAX_TRAINERS_COUNT_EMERALD 864

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
